sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:

branches:
  only:
  - master
notifications:
  email: false
before_script:
- bash ./prepare.sh
script:
- cd SwipesForScience; npm run build
after_success:
- cd ..; bash ./deploy.sh
env:
  global:
  - GH_USER: akeshavan
  - GH_REPO: brainSpot
  - secure: dDJCeJqpkFm/RQUoUr7VcKbVkhKlQA2effAWhlpiUQpa0Ybd14F8ZOWQknES9EOe4/PS+O1aUuvCVV8aJ4LF2eZx2P8ik5Ad3caetxfvZ+11HDOVADw5bwwMUzKYYj7rMrNt6e6KRQjr0/bXiu0ZEEM4TqZG5FQwh+bkkg5gN7zHr/el8D0ebIw1kriHAc6hQ2Exy7TDmIbVO994Q+H5dcWRp9C0M7cYHmY4QJBA6SdvlUlHogO5JVb2Mjd034Bpj/udlFlsF/579WlfK5Z1VhVDjIclHzZgQGFrOmLrMNcB7f1iTnmly6ynGb0m1WKfmwWqkqurGgyKllcXGjAprj3GiNJmzk0nIJe7sG25XsHUvUd8xZRT6uBarjvqNPqViQiKOKMeLqc6JoKGFMR+A6vtD5f60wiOedYk5dIB/VSc7Pb/Wcl8sGFMDbLGEEm1SWjLoLmv+MWC4FXIOHtLgSh6UA/o4dsGWmmxoz+BWpbOoMnvGRLTtijP28iqea55oAYDJI+OHHima+mSfYuGosPA8rI53XR/wg7wZ5zbUiZsWyJfmyd8jBYdqzuWYVkWYdJ21ATAhKYeuUcHxAtTCU8TTK+23St1SQDEXYbuVzqiN56NxkavEY52UVNX1ubdAAIhH5VP4wMsWNjRocK4o+4uE+8oRV/AnCAWtUVy5PU=
